In [15]:
import pandas as pd

data = {
    "Name": ["Rahim", "Karim", "Hasan", "Jamil", "Sadia"],
    "Age": [20, 25, 22, 24, 21],
    "City": ["Dhaka", "Khulna", "Dhaka", "Chattogram", "Khulna"],
    "Marks": [85, 78, 92, 88, 95]
}

df = pd.DataFrame(data)

df

    Name  Age        City  Marks
0  Rahim   20       Dhaka     85
1  Karim   25      Khulna     78
2  Hasan   22       Dhaka     92
3  Jamil   24  Chattogram     88
4  Sadia   21      Khulna     95

## Normalization
### Min Max Scaling

## 📌 Min-Max Scaling Formula

Min-Max scaling is used to normalize data into a fixed range (usually 0 to 1).

$$
X' = a + \frac{(X - X_{\min})(b - a)}{X_{\max} - X_{\min}}
$$

---

## 📖 Explanation

- \(X\) → original value  
- \(X_{\min}\) → minimum value in the dataset  
- \(X_{\max}\) → maximum value in the dataset  
- \(a\) → lower bound of the new scale (commonly 0)  
- \(b\) → upper bound of the new scale (commonly 1)  
- \(X'\) → normalized (scaled) value  

---

## 🔥 Special Case (0 to 1 Scaling)

When \(a = 0\) and \(b = 1\), the formula becomes:

$$
X' = \frac{X - X_{\min}}{X_{\max} - X_{\min}}
$$

---

## 🧠 Intuition

This formula **rescales all values proportionally** so that:
- Minimum value becomes 0
- Maximum value becomes 1
- All other values stay in between

In [16]:
df

    Name  Age        City  Marks
0  Rahim   20       Dhaka     85
1  Karim   25      Khulna     78
2  Hasan   22       Dhaka     92
3  Jamil   24  Chattogram     88
4  Sadia   21      Khulna     95

In [18]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[["Marks"]] = scaler.fit_transform(df[["Marks"]])
df.head()

    Name  Age        City     Marks
0  Rahim   20       Dhaka  0.411765
1  Karim   25      Khulna  0.000000
2  Hasan   22       Dhaka  0.823529
3  Jamil   24  Chattogram  0.588235
4  Sadia   21      Khulna  1.000000