In [25]:
import pandas as pd

data = {
    "Name": ["Rahim", "Karim", "Hasan", "Jamil", "Sadia"],
    "Age": [20, 25, 22, 24, 21],
    "City": ["Dhaka", "Khulna", "Dhaka", "Chattogram", "Khulna"],
    "Marks": [85, 78, 92, 88, 95],
    "Gender": ["Male", "Male", "Male", "Male", "Female"],
    "Outcome": ["Pass", "Fail", "Pass", "Pass", "Pass"]
}

df = pd.DataFrame(data)

df

    Name  Age        City  Marks  Gender Outcome
0  Rahim   20       Dhaka     85    Male    Pass
1  Karim   25      Khulna     78    Male    Fail
2  Hasan   22       Dhaka     92    Male    Pass
3  Jamil   24  Chattogram     88    Male    Pass
4  Sadia   21      Khulna     95  Female    Pass

In [26]:
df["Gender"]= df["Gender"].map({
    "Male":1,
    "Female":0
})
df

    Name  Age        City  Marks  Gender Outcome
0  Rahim   20       Dhaka     85       1    Pass
1  Karim   25      Khulna     78       1    Fail
2  Hasan   22       Dhaka     92       1    Pass
3  Jamil   24  Chattogram     88       1    Pass
4  Sadia   21      Khulna     95       0    Pass

In [27]:
df["Outcome"] = df["Outcome"].map({
    "Pass":1,
    "Fail":0
}
)
df

    Name  Age        City  Marks  Gender  Outcome
0  Rahim   20       Dhaka     85       1        1
1  Karim   25      Khulna     78       1        0
2  Hasan   22       Dhaka     92       1        1
3  Jamil   24  Chattogram     88       1        1
4  Sadia   21      Khulna     95       0        1

In [28]:
from sklearn.model_selection import train_test_split

X = df.drop(["Outcome"], axis=1)
y = df[["Gender"]]

X_train, y_train, X_test, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [29]:
X_train

    Name  Age        City  Marks  Gender
4  Sadia   21      Khulna     95       0
2  Hasan   22       Dhaka     92       1
0  Rahim   20       Dhaka     85       1
3  Jamil   24  Chattogram     88       1

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

## 📌 StandardScaler (Z-score Normalization)

StandardScaler transforms data so that it has **mean = 0** and **standard deviation = 1**.

---

## 📐 Formula

$$
X' = \frac{X - \mu}{\sigma}
$$

---

## 📖 Explanation

- \(X\) → original value  
- \(\mu\) → mean of the feature  
- \(\sigma\) → standard deviation of the feature  
- \(X'\) → standardized value  

---

## 🧠 Intuition

StandardScaler converts values into **how many standard deviations away from the mean** they are.

---

## 🔥 Example

If:
- \(X = 80\)  
- \(\mu = 70\)  
- \(\sigma = 10\)

Then:

$$
X' = \frac{80 - 70}{10} = 1
$$

👉 Meaning: 80 is **1 standard deviation above the mean**

---

## ⚖️ Key Idea

- Center data around 0  
- Scale variance to 1  
- Keeps distribution shape but standardizes scale

In [31]:
X_train

    Name  Age        City  Marks  Gender
4  Sadia   21      Khulna     95       0
2  Hasan   22       Dhaka     92       1
0  Rahim   20       Dhaka     85       1
3  Jamil   24  Chattogram     88       1

In [32]:
X_train = X_train[["Marks", "Gender"]]
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

array([[ 1.31306433, -1.73205081],
       [ 0.52522573,  0.57735027],
       [-1.31306433,  0.57735027],
       [-0.52522573,  0.57735027]])

---
---
 Monirul Islam 
____


---